
CREATE TABLE BOOKS(
ISBN INT,
TITLE VARCHAR2(15) NOT NULL,
CATEGORY VARCHAR2(10) NOT NULL,
AUTHOR VARCHAR2(10) NOT NULL,
PRICE INT,
LANGUAGE VARCHAR2(10),
PUBLISH_DATE DATE NOT NULL,
NO_OF_COPIES INT NOT NULL,
CONSTRAINT UC_BOOKS PRIMARY KEY (ISBN)
);


CREATE TABLE PUBLISHER(
PUBLISHER_ID INT,
PUBLISHER_NAME VARCHAR2(15) NOT NULL,
PUBLISHER_ADD VARCHAR2(25),
PUBLISHER_NO INT NOT NULL,
PUBLISHER_EMAIL VARCHAR2(11),
CONSTRAINT UC_PUB PRIMARY KEY (PUBLISHER_ID)
);


CREATE TABLE LIBRARIAN(
CNIC INT,
NAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(25),
PUB_NO INT NOT NULL,
PUB_EMAIL VARCHAR2(11),
CONSTRAINT UC_LIB PRIMARY KEY (CNIC)
);


ALTER TABLE BOOKS ADD PUB_ID INT REFERENCES PUBLISHER(PUBLISHER_ID);
ALTER TABLE BOOKS ADD LIB_ID INT REFERENCES LIBRARIAN(CNIC);

CREATE TABLE STUDENT(
STUDENT_ID INT,
NAME VARCHAR2(15) NOT NULL,
GENDER VARCHAR2(5) NOT NULL,
DOB DATE,
ADDRESS VARCHAR2(25),
PHONE_NO INT NOT NULL,
EMAIL VARCHAR2(20),
CONSTRAINT UC_STU PRIMARY KEY (STUDENT_ID)
);

ALTER TABLE BOOKS DROP COLUMN PUB_ID;
ALTER TABLE BOOKS DROP COLUMN LIB_ID;

ALTER TABLE BOOKS ADD PUB_ID INT REFERENCES PUBLISHER(PUBLISHER_ID) ON DELETE CASCADE;
ALTER TABLE BOOKS ADD LIB_ID INT REFERENCES LIBRARIAN(CNIC) ON DELETE CASCADE;

DESC BOOKS;


CREATE TABLE BORROW(
ISSUE_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL,
RETURN_ACTUAL_DATE DATE NOT NULL,
FINE INT NOT NULL,
STUDENT_ID INT REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
ISBN INT REFERENCES BOOKS(ISBN) ON DELETE CASCADE,
CONSTRAINT UC_BORROW PRIMARY KEY(ISBN,STUDENT_ID)
);

DESC PUBLISHER;

SELECT *FROM LIBRARIAN;
DESC STUDENT;

SELECT *FROM STUDENT ORDER BY STUDENT_ID;

UPDATE STUDENT SET PASSWORD='123456' WHERE PASSWORD IS NULL;
INSERT INTO STUDENT values(2, 'Hafsa' , 'F', '07-march-1999', 'Fsd', '04375462786', 'hafsa@gmail.com', 'hafsa');

ALTER TABLE LIBRARIAN ADD (PASSWORD VARCHAR2(10));

ALTER TABLE LIBRARIAN MODIFY(LIB_EMAIL VARCHAR2(30));

INSERT INTO LIBRARIAN VALUES(3320218, 'Kashif', 'Multan', 1, 'kashif@gmail.com', 'kashif');
INSERT INTO LIBRARIAN VALUES(3320275, 'imran', 'Multan', 2, 'imran@gmail.com', 'imran');
INSERT INTO LIBRARIAN VALUES(33202-75, 'Ali', 'DGK', 3,'Ali@gmail.com', 'ali');

SELECT *FROM LIBRARIAN;

CREATE SEQUENCE STUD_SEQ
MINVALUE 1
MAXVALUE 1000
START WITH 5
INCREMENT BY 1;

INSERT INTO STUDENT VALUES(STUD_SEQ.NEXTVAL, 'Ali', 'M', '07-Nov-2004', 'Khanawal', '03145678921', 'Ali@gmail.com', 'Ali314');

ALTER TABLE BOOKS MODIFY(TITLE VARCHAR2(30), CATEGORY VARCHAR2(30), AUTHOR VARCHAR2(30));

DESC PUBLISHER;

CREATE SEQUENCE PUB_SEQ
MINVALUE 1001
MAXVALUE 10000
START WITH 1001
INCREMENT BY 1;

INSERT INTO PUBLISHER VALUES(PUB_SEQ.NEXTVAL, 'KAMRAN', 'JHANG', '03245789569','KAMRAN@GMAIL.COM');
INSERT INTO PUBLISHER VALUES(PUB_SEQ.NEXTVAL, 'IMTIAZ', 'FSD', '03136789217','IMTIAZ@GMAIL.COM');
INSERT INTO PUBLISHER VALUES(PUB_SEQ.NEXTVAL, 'ALI AKMAL', 'JHANG', '03146756566','ALIAKMAL@GMAIL.COM');
INSERT INTO PUBLISHER VALUES(PUB_SEQ.NEXTVAL, 'ZEESHAN', 'LHR', '03456712309','ZEESHAN@GMAIL.COM');

/*INSERT DATA INTO BOOKS TABLE*/
INSERT INTO BOOKS VALUES(12345,'INTRO TO C++', 'STUDY','ROBERT LAFORE',500,'ENGLISH','16-JUNE-2003',5,1002,3320275);


INSERT INTO BOOKS VALUES(12345,'INTRO TO C++', 'STUDY','ROBERT LAFORE',500,'ENGLISH','16-JUNE-2003',5,1002,3320217843);
INSERT INTO BOOKS VALUES(23453,'DBMS', 'STUDY','CATHERINE RICARDO',1000,'ENGLISH','05-NOV-2001',2,1001,332021826);

ALTER TABLE BOOKS DROP COLUMN NO_OF_BOOKS;
ALTER TABLE BOOKS ADD STATUS VARCHAR2(15);
DESC BOOKS;

CREATE OR REPLACE TRIGGER STUDENT_ID
BEFORE INSERT ON STUDENT
FOR EACH ROW
DECLARE 
P_KEY INT;
BEGIN 
SELECT LPAD(STUD_SEQ.NEXTVAL,4,'0') INTO P_KEY FROM DUAL;
:NEW.student_ID := '' ||P_KEY;
END;
/

CREATE OR REPLACE TRIGGER PUBLI_ID
BEFORE INSERT ON PUBLISHER
FOR EACH ROW
DECLARE 
PUB_KEY INT;
BEGIN 
SELECT LPAD(PUB_SEQ.NEXTVAL,4,'0') INTO PUB_KEY FROM DUAL;
:NEW.PUBLISHER_ID := '' || PUB_KEY;
END;
/

ALTER TABLE student
ADD (photo_id blob); 

alter table student add (roll_no int not null unique, class varchar2(30) not null);

delete from student where student_id between 1 and 7;

insert into student(roll_no, name, class,gender,phone_no,email,password, photo_id) values (1001,'iqra', '1st year', 'fmale' ,'0357364658','iqra@gmail.com','iqra4546', bfilename('C:\oracle\sqldeveloper-20.2.0.175.1842-x64\sqldeveloper','icon.png'));

alter table student drop column photo_id;

alter table student add photo_id bfile;

desc student;

select *from student;


CREATE VIEW issuestudent AS Select borrow.roll_no,student.name,borrow.issue_date,borrow.return_actual_date,borrow.isbn,student.class from student inner join borrow on borrow.roll_no = student.roll_no;

CREATE VIEW returnstudent AS SELECT return.ROLL_NO,student.name,return.RETURN_DATE,return.RETURN_ACTUAL_dATE, return.ISBN,student.CLASS FROM STUDENT INNER JOIN RETURN ON RETURN.ROLL_NO = STUDENT.ROLL_NO;

CREATE VIEW studentview AS select name,roll_no,gender dob, address,phone_no,class,email,photo_id from student;